import "dotenv/config";
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import bcrypt from "bcryptjs";

const url = process.env.DATABASE_URL ?? "file:./prisma/dev.db";
const authToken = process.env.TURSO_AUTH_TOKEN;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const prisma = new PrismaClient({ adapter: new PrismaLibSql({ url, ...(authToken ? { authToken } : {}) }) } as any);

const properties = [
  // === TORONTO - DOWNTOWN CORE ===
  {
    address: "100 King St W",
    city: "Toronto",
    neighborhood: "Financial District",
    submarket: "Downtown Toronto",
    lat: 43.6483,
    lng: -79.3831,
    propertyType: "OFFICE",
    propertySubtype: "Class A Office",
    zoning: "CRE",
    buildingSize: 48000,
    lotSize: 12000,
    yearBuilt: 1988,
    numFloors: 12,
    parkingSpaces: 180,
    status: "FOR_SALE",
    askingPrice: 25800000,
    listedDate: new Date("2025-12-01"),
    daysOnMarket: 89,
    noi: 1341600,
    capRate: 0.052,
    grm: 14.8,
    pricePerSqFt: 537.5,
    grossRevenue: 1968000,
    operatingExpenses: 626400,
    vacancyRate: 0.05,
    taxesAnnual: 312000,
    description: "Trophy Class A office tower in Toronto's Financial District with high ceilings, modernized lobbies, and premium tenant roster. Excellent transit access steps from King Station.",
    highlights: JSON.stringify(["Corner location", "LEED Gold certified", "Modernized common areas", "Full floor availability", "Steps to TTC King Station"]),
    listingBrokerage: "CBRE Canada",
    tenants: [
      { name: "Deloitte Canada", industry: "Professional Services", leaseType: "GROSS", leaseExpiry: new Date("2028-06-30"), rentPerSqFt: 38, squareFeet: 22000, percentageOfBuilding: 45.8, creditRating: "Investment Grade" },
      { name: "TD Bank", industry: "Financial Services", leaseType: "GROSS", leaseExpiry: new Date("2027-03-31"), rentPerSqFt: 42, squareFeet: 10000, percentageOfBuilding: 20.8, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 27500000, date: new Date("2025-10-01"), priceType: "ASKING", notes: "Original listing price" },
      { price: 25800000, date: new Date("2025-12-01"), priceType: "PRICE_CHANGE", notes: "Price reduction" },
      { price: 21400000, date: new Date("2023-06-15"), priceType: "ASSESSMENT", notes: "MPAC assessment" },
    ],
  },
  {
    address: "1235 Bay St",
    city: "Toronto",
    neighborhood: "Bloor-Yorkville",
    submarket: "Midtown Toronto",
    lat: 43.6694,
    lng: -79.3916,
    propertyType: "MIXED_USE",
    propertySubtype: "Retail/Office Mixed",
    zoning: "CR3.5",
    buildingSize: 28500,
    lotSize: 7200,
    yearBuilt: 1972,
    numFloors: 6,
    numUnits: 8,
    parkingSpaces: 42,
    status: "SOLD",
    askingPrice: 19200000,
    soldPrice: 18750000,
    soldDate: new Date("2025-09-22"),
    listedDate: new Date("2025-05-15"),
    daysOnMarket: 130,
    noi: 1087500,
    capRate: 0.058,
    pricePerSqFt: 657.9,
    grossRevenue: 1548000,
    operatingExpenses: 460500,
    vacancyRate: 0.03,
    taxesAnnual: 186000,
    description: "Prime Yorkville mixed-use building with ground-floor luxury retail and five floors of boutique office space. Prestigious address with excellent foot traffic.",
    highlights: JSON.stringify(["Ground floor retail leased to national retailer", "Walk score 99", "Rare Yorkville freehold ownership", "Steps to Bay Station"]),
    listingBrokerage: "Colliers International",
    tenants: [
      { name: "Lululemon", industry: "Retail", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2029-01-31"), rentPerSqFt: 95, squareFeet: 4200, percentageOfBuilding: 14.7, creditRating: "National Tenant" },
      { name: "Benevolent AI", industry: "Technology", leaseType: "GROSS", leaseExpiry: new Date("2027-08-31"), rentPerSqFt: 35, squareFeet: 8000, percentageOfBuilding: 28.1 },
    ],
    priceHistory: [
      { price: 19200000, date: new Date("2025-05-15"), priceType: "ASKING" },
      { price: 18750000, date: new Date("2025-09-22"), priceType: "SOLD" },
      { price: 14800000, date: new Date("2021-11-08"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "750 Lawrence Ave E",
    city: "Toronto",
    neighborhood: "Victoria Village",
    submarket: "East Toronto Industrial",
    lat: 43.7299,
    lng: -79.3248,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Warehouse/Distribution",
    zoning: "EH",
    buildingSize: 84000,
    lotSize: 185000,
    yearBuilt: 1968,
    numFloors: 1,
    parkingSpaces: 95,
    loadingDocks: 14,
    clearHeight: 24,
    status: "FOR_SALE",
    askingPrice: 34200000,
    listedDate: new Date("2025-11-15"),
    daysOnMarket: 45,
    noi: 2053200,
    capRate: 0.060,
    pricePerSqFt: 407.1,
    grossRevenue: 2688000,
    operatingExpenses: 634800,
    vacancyRate: 0.0,
    taxesAnnual: 245000,
    description: "Rare freestanding industrial facility on 4.25 acres with excellent highway access. Fully leased to single tenant on long-term NNN lease. Strong rental growth potential at lease expiry.",
    highlights: JSON.stringify(["Fully leased NNN", "4.25 acre site", "14 truck-level doors", "24' clear height", "DVP/401 access"]),
    listingBrokerage: "JLL Canada",
    tenants: [
      { name: "Loblaws Companies", industry: "Food Distribution", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2030-12-31"), rentPerSqFt: 32, squareFeet: 84000, percentageOfBuilding: 100, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 34200000, date: new Date("2025-11-15"), priceType: "ASKING" },
      { price: 18600000, date: new Date("2019-03-20"), priceType: "SOLD", notes: "Prior acquisition" },
    ],
  },
  {
    address: "2090 Danforth Ave",
    city: "Toronto",
    neighborhood: "The Danforth",
    submarket: "East Toronto Retail",
    lat: 43.6917,
    lng: -79.3148,
    propertyType: "RETAIL",
    propertySubtype: "Street Retail",
    zoning: "CR2.0",
    buildingSize: 12500,
    lotSize: 8400,
    yearBuilt: 1955,
    numFloors: 2,
    parkingSpaces: 18,
    status: "FOR_SALE",
    askingPrice: 7200000,
    listedDate: new Date("2025-10-20"),
    daysOnMarket: 71,
    noi: 396000,
    capRate: 0.055,
    pricePerSqFt: 576.0,
    grossRevenue: 562500,
    operatingExpenses: 166500,
    vacancyRate: 0.0,
    taxesAnnual: 78000,
    description: "Fully occupied two-storey retail/commercial building on high-traffic Danforth Ave. Three street-level retail units plus upper office space. Excellent transit connectivity.",
    highlights: JSON.stringify(["100% occupied", "Transit-oriented location", "Diverse tenant mix", "Income-producing from day 1", "Coxwell Station nearby"]),
    listingBrokerage: "Marcus & Millichap",
    tenants: [
      { name: "Second Cup", industry: "Food & Beverage", leaseType: "MODIFIED_GROSS", leaseExpiry: new Date("2027-05-31"), rentPerSqFt: 48, squareFeet: 1800, creditRating: "National Tenant" },
      { name: "Pharmacy Plus", industry: "Healthcare Retail", leaseType: "MODIFIED_GROSS", leaseExpiry: new Date("2028-11-30"), rentPerSqFt: 42, squareFeet: 2400 },
    ],
    priceHistory: [
      { price: 7200000, date: new Date("2025-10-20"), priceType: "ASKING" },
      { price: 4850000, date: new Date("2018-07-14"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "360 Dufferin St",
    city: "Toronto",
    neighborhood: "Dufferin Grove",
    submarket: "West Toronto Industrial",
    lat: 43.6426,
    lng: -79.4284,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Industrial Flex",
    zoning: "IC",
    buildingSize: 36500,
    lotSize: 48000,
    yearBuilt: 1981,
    numFloors: 2,
    parkingSpaces: 55,
    loadingDocks: 4,
    clearHeight: 18,
    status: "FOR_SALE",
    askingPrice: 15400000,
    listedDate: new Date("2025-09-08"),
    daysOnMarket: 83,
    noi: 985600,
    capRate: 0.064,
    pricePerSqFt: 421.9,
    grossRevenue: 1387000,
    operatingExpenses: 401400,
    vacancyRate: 0.08,
    taxesAnnual: 128000,
    description: "Versatile industrial flex building in prime west Toronto location. Mix of warehouse/distribution and office space. Close proximity to Gardiner and Allen Road.",
    highlights: JSON.stringify(["Flex industrial", "Office component", "City infill location", "Redevelopment upside"]),
    listingBrokerage: "Avison Young",
    tenants: [
      { name: "CanPrint Communications", industry: "Printing/Manufacturing", leaseType: "MODIFIED_GROSS", leaseExpiry: new Date("2027-02-28"), rentPerSqFt: 26, squareFeet: 28000, percentageOfBuilding: 76.7 },
    ],
    priceHistory: [
      { price: 16800000, date: new Date("2025-07-01"), priceType: "ASKING" },
      { price: 15400000, date: new Date("2025-09-08"), priceType: "PRICE_CHANGE" },
    ],
  },
  {
    address: "55 St Clair Ave W",
    city: "Toronto",
    neighborhood: "Deer Park",
    submarket: "Midtown Toronto",
    lat: 43.6879,
    lng: -79.4001,
    propertyType: "OFFICE",
    propertySubtype: "Class B Office",
    zoning: "CR4.5",
    buildingSize: 22000,
    lotSize: 6800,
    yearBuilt: 1969,
    numFloors: 8,
    parkingSpaces: 65,
    status: "FOR_SALE",
    askingPrice: 12400000,
    listedDate: new Date("2025-08-12"),
    daysOnMarket: 110,
    noi: 892800,
    capRate: 0.072,
    pricePerSqFt: 563.6,
    grossRevenue: 1188000,
    operatingExpenses: 295200,
    vacancyRate: 0.12,
    taxesAnnual: 145000,
    description: "Well-located midtown office building steps from St. Clair subway station. Value-add opportunity with below-market rents and near-term lease rollovers. Significant rental upside.",
    highlights: JSON.stringify(["Subway steps away", "Value-add opportunity", "Below-market rents", "Residential conversion potential", "Great St. Clair retail node"]),
    listingBrokerage: "Cushman & Wakefield",
    priceHistory: [
      { price: 12400000, date: new Date("2025-08-12"), priceType: "ASKING" },
      { price: 9200000, date: new Date("2020-02-28"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "400 Wellington St W",
    city: "Toronto",
    neighborhood: "King West",
    submarket: "Downtown Toronto",
    lat: 43.6452,
    lng: -79.3996,
    propertyType: "MULTIFAMILY",
    propertySubtype: "Apartment Building",
    zoning: "RA",
    buildingSize: 38400,
    lotSize: 14000,
    yearBuilt: 1962,
    numFloors: 6,
    numUnits: 38,
    parkingSpaces: 32,
    status: "FOR_SALE",
    askingPrice: 15600000,
    listedDate: new Date("2025-11-01"),
    daysOnMarket: 59,
    noi: 655200,
    capRate: 0.042,
    pricePerSqFt: 406.25,
    grossRevenue: 936000,
    operatingExpenses: 280800,
    vacancyRate: 0.02,
    taxesAnnual: 124000,
    description: "Stabilized 38-unit apartment building in sought-after King West neighbourhood. Mix of bachelor, 1BR and 2BR suites. Long-term holds rare in this micromarket.",
    highlights: JSON.stringify(["Prime King West location", "38 residential units", "Below-market rents with upside", "Full occupancy", "Walk score 95"]),
    listingBrokerage: "CBRE Capital Markets",
    priceHistory: [
      { price: 15600000, date: new Date("2025-11-01"), priceType: "ASKING" },
      { price: 8400000, date: new Date("2016-04-15"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "940 Warden Ave",
    city: "Toronto",
    neighborhood: "Warden Woods",
    submarket: "East Toronto Industrial",
    lat: 43.7183,
    lng: -79.2891,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Distribution Centre",
    zoning: "EH",
    buildingSize: 98000,
    lotSize: 210000,
    yearBuilt: 1974,
    numFloors: 1,
    parkingSpaces: 120,
    loadingDocks: 18,
    clearHeight: 26,
    status: "SOLD",
    askingPrice: 44000000,
    soldPrice: 42800000,
    soldDate: new Date("2025-10-31"),
    listedDate: new Date("2025-07-08"),
    daysOnMarket: 115,
    noi: 2654000,
    capRate: 0.062,
    pricePerSqFt: 436.7,
    grossRevenue: 3430000,
    operatingExpenses: 776000,
    vacancyRate: 0.0,
    taxesAnnual: 315000,
    description: "Core GTA industrial asset sold to institutional investor. Single-tenant NNN lease to investment-grade tenant with long-term tenure. Rare 4.8-acre site in established industrial node.",
    highlights: JSON.stringify(["Institutional quality asset", "4.8 acres", "18 truck-level doors", "Investment grade tenant", "Long WALT"]),
    listingBrokerage: "JLL Canada",
    tenants: [
      { name: "Rexel Canada", industry: "Electrical Distribution", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2032-06-30"), rentPerSqFt: 35, squareFeet: 98000, percentageOfBuilding: 100, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 44000000, date: new Date("2025-07-08"), priceType: "ASKING" },
      { price: 42800000, date: new Date("2025-10-31"), priceType: "SOLD" },
      { price: 26500000, date: new Date("2020-11-20"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "1401 Wilson Ave",
    city: "Toronto",
    neighborhood: "Downsview",
    submarket: "North York",
    lat: 43.7496,
    lng: -79.4851,
    propertyType: "OFFICE",
    propertySubtype: "Class B Office",
    zoning: "EO",
    buildingSize: 38000,
    lotSize: 32000,
    yearBuilt: 1985,
    numFloors: 5,
    parkingSpaces: 145,
    status: "FOR_SALE",
    askingPrice: 16200000,
    listedDate: new Date("2025-06-22"),
    daysOnMarket: 161,
    noi: 1263600,
    capRate: 0.078,
    pricePerSqFt: 426.3,
    grossRevenue: 1634000,
    operatingExpenses: 370400,
    vacancyRate: 0.15,
    taxesAnnual: 198000,
    description: "Suburban office complex near Hwy 401 interchange. Good natural light, ample surface parking, and attractive suburban rents. Value-add opportunity in recovering North York office submarket.",
    highlights: JSON.stringify(["Highway 401 proximity", "Ample surface parking ratio", "Value-add with lease-up", "Near Sheppard-Allen LRT"]),
    listingBrokerage: "Avison Young",
    priceHistory: [
      { price: 17800000, date: new Date("2025-04-01"), priceType: "ASKING" },
      { price: 16200000, date: new Date("2025-06-22"), priceType: "PRICE_CHANGE" },
    ],
  },
  {
    address: "189 George St",
    city: "Toronto",
    neighborhood: "Moss Park",
    submarket: "Downtown East",
    lat: 43.6550,
    lng: -79.3713,
    propertyType: "MULTIFAMILY",
    propertySubtype: "Apartment Building",
    zoning: "RA",
    buildingSize: 26400,
    lotSize: 9200,
    yearBuilt: 1958,
    numFloors: 4,
    numUnits: 26,
    parkingSpaces: 14,
    status: "FOR_SALE",
    askingPrice: 10200000,
    listedDate: new Date("2025-12-05"),
    daysOnMarket: 25,
    noi: 459000,
    capRate: 0.045,
    pricePerSqFt: 386.4,
    grossRevenue: 655200,
    operatingExpenses: 196200,
    vacancyRate: 0.0,
    taxesAnnual: 82000,
    description: "Well-maintained 26-unit apartment building in emerging downtown east neighbourhood. Gentrification driven by proximity to new condo developments and Distillery District.",
    highlights: JSON.stringify(["Fully occupied", "Downtown east revitalization", "Redevelopment land value", "Heritage character building"]),
    listingBrokerage: "Marcus & Millichap",
    priceHistory: [
      { price: 10200000, date: new Date("2025-12-05"), priceType: "ASKING" },
      { price: 5800000, date: new Date("2017-09-12"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },

  // === MISSISSAUGA ===
  {
    address: "2 Robert Speck Pkwy",
    city: "Mississauga",
    neighborhood: "City Centre",
    submarket: "Mississauga CBD",
    lat: 43.5930,
    lng: -79.6367,
    propertyType: "OFFICE",
    propertySubtype: "Class A Office",
    zoning: "CC1",
    buildingSize: 64000,
    lotSize: 28000,
    yearBuilt: 1991,
    numFloors: 8,
    parkingSpaces: 280,
    status: "FOR_SALE",
    askingPrice: 29800000,
    listedDate: new Date("2025-10-15"),
    daysOnMarket: 76,
    noi: 1967000,
    capRate: 0.066,
    pricePerSqFt: 465.6,
    grossRevenue: 2688000,
    operatingExpenses: 721000,
    vacancyRate: 0.10,
    taxesAnnual: 378000,
    description: "Prominent Class A office tower in Mississauga City Centre. Premium amenities including on-site fitness facility, conference centre, and immediate access to Square One Shopping Centre.",
    highlights: JSON.stringify(["Square One access", "LEED EB Gold", "On-site fitness centre", "Conference facility", "LRT proximity"]),
    listingBrokerage: "CBRE Canada",
    tenants: [
      { name: "Rogers Communications", industry: "Telecommunications", leaseType: "GROSS", leaseExpiry: new Date("2029-06-30"), rentPerSqFt: 32, squareFeet: 28000, creditRating: "Investment Grade" },
      { name: "PwC Canada", industry: "Professional Services", leaseType: "GROSS", leaseExpiry: new Date("2028-03-31"), rentPerSqFt: 34, squareFeet: 16000, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 29800000, date: new Date("2025-10-15"), priceType: "ASKING" },
      { price: 22400000, date: new Date("2021-05-30"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "7045 Edwards Blvd",
    city: "Mississauga",
    neighborhood: "Airport Corporate Centre",
    submarket: "Mississauga Airport",
    lat: 43.6689,
    lng: -79.6528,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Distribution Centre",
    zoning: "E2",
    buildingSize: 124000,
    lotSize: 320000,
    yearBuilt: 2002,
    numFloors: 1,
    parkingSpaces: 145,
    loadingDocks: 22,
    clearHeight: 32,
    status: "FOR_SALE",
    askingPrice: 57600000,
    listedDate: new Date("2025-09-22"),
    daysOnMarket: 69,
    noi: 3456000,
    capRate: 0.060,
    pricePerSqFt: 464.5,
    grossRevenue: 4340000,
    operatingExpenses: 884000,
    vacancyRate: 0.0,
    taxesAnnual: 486000,
    description: "Modern institutional-grade distribution centre near Pearson Airport. 32-foot clear height, ESFR sprinkler system, cross-dock configuration. Fully leased to credit tenant on long-term NNN lease.",
    highlights: JSON.stringify(["Pearson Airport adjacency", "32' clear height", "Cross-dock", "ESFR sprinklers", "Institutional grade"]),
    listingBrokerage: "JLL Canada",
    tenants: [
      { name: "Amazon Canada", industry: "E-commerce/Logistics", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2031-08-31"), rentPerSqFt: 35, squareFeet: 124000, percentageOfBuilding: 100, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 57600000, date: new Date("2025-09-22"), priceType: "ASKING" },
      { price: 36200000, date: new Date("2019-07-18"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "3085 Hurontario St",
    city: "Mississauga",
    neighborhood: "Mississauga Valleys",
    submarket: "Mississauga Corridor",
    lat: 43.5648,
    lng: -79.6396,
    propertyType: "RETAIL",
    propertySubtype: "Anchored Retail Plaza",
    zoning: "C3",
    buildingSize: 47500,
    lotSize: 185000,
    yearBuilt: 1989,
    numFloors: 1,
    parkingSpaces: 285,
    status: "SOLD",
    askingPrice: 21400000,
    soldPrice: 20100000,
    soldDate: new Date("2025-11-14"),
    listedDate: new Date("2025-06-01"),
    daysOnMarket: 166,
    noi: 1386900,
    capRate: 0.069,
    pricePerSqFt: 423.2,
    grossRevenue: 1900000,
    operatingExpenses: 513100,
    vacancyRate: 0.05,
    taxesAnnual: 224000,
    description: "Grocery-anchored strip plaza on high-traffic Hurontario corridor sold in Q4 2025. Anchor tenant provides stability with junior anchor and in-line tenants providing rental upside.",
    highlights: JSON.stringify(["Grocery anchored", "High-traffic Hurontario", "Strong demographics", "Long WALT", "Redevelopment land value"]),
    listingBrokerage: "Colliers International",
    tenants: [
      { name: "No Frills (Loblaws)", industry: "Grocery", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2031-01-31"), rentPerSqFt: 18, squareFeet: 22000, creditRating: "Investment Grade" },
      { name: "Shoppers Drug Mart", industry: "Pharmacy", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2028-09-30"), rentPerSqFt: 28, squareFeet: 10000, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 21400000, date: new Date("2025-06-01"), priceType: "ASKING" },
      { price: 20100000, date: new Date("2025-11-14"), priceType: "SOLD" },
      { price: 14600000, date: new Date("2018-03-28"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "980 Matheson Blvd E",
    city: "Mississauga",
    neighborhood: "Dixie",
    submarket: "Mississauga East Industrial",
    lat: 43.6218,
    lng: -79.5840,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Manufacturing/Warehouse",
    zoning: "E2",
    buildingSize: 172000,
    lotSize: 490000,
    yearBuilt: 1986,
    numFloors: 1,
    parkingSpaces: 215,
    loadingDocks: 28,
    clearHeight: 22,
    status: "SOLD",
    askingPrice: 79800000,
    soldPrice: 76400000,
    soldDate: new Date("2025-08-19"),
    listedDate: new Date("2025-03-01"),
    daysOnMarket: 171,
    noi: 4126000,
    capRate: 0.054,
    pricePerSqFt: 444.2,
    grossRevenue: 5160000,
    operatingExpenses: 1034000,
    vacancyRate: 0.0,
    taxesAnnual: 624000,
    description: "Major industrial sale in core Mississauga industrial corridor. 11.25-acre site with significant land value. Multi-tenant facility fully leased with staggered lease maturities.",
    highlights: JSON.stringify(["11.25 acres", "Multi-tenant", "Core industrial location", "Hwy 410/427 access", "Major transaction"]),
    listingBrokerage: "CBRE Capital Markets",
    priceHistory: [
      { price: 79800000, date: new Date("2025-03-01"), priceType: "ASKING" },
      { price: 76400000, date: new Date("2025-08-19"), priceType: "SOLD" },
      { price: 44200000, date: new Date("2018-06-30"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "5925 Airport Rd",
    city: "Mississauga",
    neighborhood: "Airport Corporate Centre",
    submarket: "Mississauga Airport",
    lat: 43.6912,
    lng: -79.6384,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Air Cargo/Logistics",
    zoning: "E3",
    buildingSize: 91000,
    lotSize: 245000,
    yearBuilt: 1997,
    numFloors: 1,
    parkingSpaces: 112,
    loadingDocks: 16,
    clearHeight: 28,
    status: "FOR_SALE",
    askingPrice: 41800000,
    listedDate: new Date("2025-11-28"),
    daysOnMarket: 32,
    noi: 2422400,
    capRate: 0.058,
    pricePerSqFt: 459.3,
    grossRevenue: 3094000,
    operatingExpenses: 671600,
    vacancyRate: 0.0,
    taxesAnnual: 358000,
    description: "Strategic air cargo logistics facility adjacent to Pearson International Airport. Rare airside proximity with office component. Single tenant fully NNN leased.",
    highlights: JSON.stringify(["Pearson adjacency", "28' clear height", "Rare airport location", "NNN lease", "Air cargo positioning"]),
    listingBrokerage: "Avison Young",
    priceHistory: [
      { price: 41800000, date: new Date("2025-11-28"), priceType: "ASKING" },
    ],
  },

  // === BRAMPTON ===
  {
    address: "55 West Dr",
    city: "Brampton",
    neighborhood: "Brampton West Industrial",
    submarket: "Brampton Industrial",
    lat: 43.6872,
    lng: -79.7523,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Distribution Centre",
    zoning: "M3",
    buildingSize: 185000,
    lotSize: 520000,
    yearBuilt: 2008,
    numFloors: 1,
    parkingSpaces: 225,
    loadingDocks: 32,
    clearHeight: 36,
    status: "FOR_SALE",
    askingPrice: 82400000,
    listedDate: new Date("2025-10-08"),
    daysOnMarket: 83,
    noi: 4694000,
    capRate: 0.057,
    pricePerSqFt: 445.4,
    grossRevenue: 5920000,
    operatingExpenses: 1226000,
    vacancyRate: 0.0,
    taxesAnnual: 594000,
    description: "Best-in-class distribution facility on 11.9 acres in Brampton's premier industrial node. 36-foot clear height with ESFR sprinklers. Major food-grade tenant on long-term NNN lease.",
    highlights: JSON.stringify(["36' clear height", "11.9 acres", "ESFR sprinklers", "Food-grade certified", "401/410 access"]),
    listingBrokerage: "JLL Canada",
    tenants: [
      { name: "Maple Leaf Foods", industry: "Food Manufacturing", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2033-03-31"), rentPerSqFt: 32, squareFeet: 185000, percentageOfBuilding: 100, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 82400000, date: new Date("2025-10-08"), priceType: "ASKING" },
      { price: 48600000, date: new Date("2020-08-14"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "7700 Hurontario St",
    city: "Brampton",
    neighborhood: "Hurontario",
    submarket: "Brampton Retail",
    lat: 43.7216,
    lng: -79.7188,
    propertyType: "RETAIL",
    propertySubtype: "Power Centre",
    zoning: "SC",
    buildingSize: 42000,
    lotSize: 225000,
    yearBuilt: 2001,
    numFloors: 1,
    parkingSpaces: 320,
    status: "FOR_SALE",
    askingPrice: 18600000,
    listedDate: new Date("2025-07-15"),
    daysOnMarket: 138,
    noi: 1320600,
    capRate: 0.071,
    pricePerSqFt: 442.9,
    grossRevenue: 1764000,
    operatingExpenses: 443400,
    vacancyRate: 0.05,
    taxesAnnual: 218000,
    description: "Established power centre on high-traffic Hurontario Street in Brampton's major retail node. National anchors with strong covenant strength. Stable income stream.",
    highlights: JSON.stringify(["National tenant anchors", "High traffic Hurontario", "Power centre format", "Strong demographics", "New LRT corridor"]),
    listingBrokerage: "Colliers International",
    tenants: [
      { name: "Home Depot Canada", industry: "Home Improvement", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2030-06-30"), rentPerSqFt: 22, squareFeet: 22000, creditRating: "Investment Grade" },
      { name: "SportChek", industry: "Sporting Goods", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2028-01-31"), rentPerSqFt: 32, squareFeet: 8000, creditRating: "National Tenant" },
    ],
    priceHistory: [
      { price: 20200000, date: new Date("2025-05-01"), priceType: "ASKING" },
      { price: 18600000, date: new Date("2025-07-15"), priceType: "PRICE_CHANGE" },
    ],
  },
  {
    address: "2 Automatic Rd",
    city: "Brampton",
    neighborhood: "Steeles Industrial",
    submarket: "Brampton Industrial",
    lat: 43.6584,
    lng: -79.7346,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Manufacturing Facility",
    zoning: "M2",
    buildingSize: 95000,
    lotSize: 298000,
    yearBuilt: 1979,
    numFloors: 1,
    parkingSpaces: 116,
    loadingDocks: 12,
    clearHeight: 20,
    status: "SOLD",
    askingPrice: 39800000,
    soldPrice: 38200000,
    soldDate: new Date("2025-07-30"),
    listedDate: new Date("2025-02-15"),
    daysOnMarket: 165,
    noi: 2406600,
    capRate: 0.063,
    pricePerSqFt: 402.1,
    grossRevenue: 2984000,
    operatingExpenses: 577400,
    vacancyRate: 0.0,
    taxesAnnual: 298000,
    description: "Core Brampton industrial sold in 2025. Established manufacturing facility on 6.85 acres. Multi-tenant with staggered leases providing income diversity.",
    highlights: JSON.stringify(["6.85 acres", "Multi-tenant", "Manufacturing grade", "Hwy 410 access", "Established industrial node"]),
    listingBrokerage: "CBRE Canada",
    priceHistory: [
      { price: 39800000, date: new Date("2025-02-15"), priceType: "ASKING" },
      { price: 38200000, date: new Date("2025-07-30"), priceType: "SOLD" },
      { price: 22400000, date: new Date("2017-11-22"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },

  // === HAMILTON ===
  {
    address: "1 James St N",
    city: "Hamilton",
    neighborhood: "Downtown Hamilton",
    submarket: "Hamilton Downtown",
    lat: 43.2578,
    lng: -79.8702,
    propertyType: "MIXED_USE",
    propertySubtype: "Heritage Mixed-Use",
    zoning: "D1",
    buildingSize: 19500,
    lotSize: 7800,
    yearBuilt: 1912,
    numFloors: 5,
    numUnits: 12,
    parkingSpaces: 0,
    status: "FOR_SALE",
    askingPrice: 8400000,
    listedDate: new Date("2025-10-28"),
    daysOnMarket: 62,
    noi: 655200,
    capRate: 0.078,
    pricePerSqFt: 430.8,
    grossRevenue: 924000,
    operatingExpenses: 268800,
    vacancyRate: 0.0,
    taxesAnnual: 78000,
    description: "Iconic heritage building in Hamilton's revitalized downtown core. Ground floor restaurant and retail anchors with 12 residential units above. Hamilton's thriving arts district location.",
    highlights: JSON.stringify(["Heritage property", "100% occupied", "Downtown arts district", "Restaurant ground floor", "Residential rental upside"]),
    listingBrokerage: "Royal LePage Commercial",
    priceHistory: [
      { price: 8400000, date: new Date("2025-10-28"), priceType: "ASKING" },
      { price: 4200000, date: new Date("2016-05-12"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "500 Barton St E",
    city: "Hamilton",
    neighborhood: "Crown Point",
    submarket: "Hamilton Industrial",
    lat: 43.2628,
    lng: -79.8255,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Heavy Industrial",
    zoning: "M10",
    buildingSize: 148000,
    lotSize: 620000,
    yearBuilt: 1958,
    numFloors: 1,
    parkingSpaces: 182,
    loadingDocks: 8,
    clearHeight: 18,
    status: "FOR_SALE",
    askingPrice: 52400000,
    listedDate: new Date("2025-08-20"),
    daysOnMarket: 102,
    noi: 3774000,
    capRate: 0.072,
    pricePerSqFt: 354.1,
    grossRevenue: 4640000,
    operatingExpenses: 866000,
    vacancyRate: 0.0,
    taxesAnnual: 412000,
    description: "Significant heavy industrial property on 14.2 acres in Hamilton's established harbour industrial area. Rare M10 zoning permits wide range of industrial uses.",
    highlights: JSON.stringify(["14.2 acres", "M10 heavy industrial zoning", "Harbour proximity", "Rail siding access", "Large lot with expansion potential"]),
    listingBrokerage: "Avison Young",
    priceHistory: [
      { price: 52400000, date: new Date("2025-08-20"), priceType: "ASKING" },
      { price: 28600000, date: new Date("2015-09-18"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "20 Copeland Ave",
    city: "Hamilton",
    neighborhood: "Hamilton Industrial Core",
    submarket: "Hamilton Industrial",
    lat: 43.2456,
    lng: -79.8534,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Warehouse/Distribution",
    zoning: "M3",
    buildingSize: 228000,
    lotSize: 580000,
    yearBuilt: 1971,
    numFloors: 1,
    parkingSpaces: 268,
    loadingDocks: 34,
    clearHeight: 24,
    status: "SOLD",
    askingPrice: 72000000,
    soldPrice: 69800000,
    soldDate: new Date("2025-06-15"),
    listedDate: new Date("2025-01-10"),
    daysOnMarket: 156,
    noi: 5306000,
    capRate: 0.076,
    pricePerSqFt: 306.1,
    grossRevenue: 6384000,
    operatingExpenses: 1078000,
    vacancyRate: 0.0,
    taxesAnnual: 684000,
    description: "Landmark Hamilton industrial portfolio acquisition. 13.3-acre site with exceptional warehouse specifications. Fully occupied multi-tenant facility sold to REIT in off-market transaction.",
    highlights: JSON.stringify(["13.3 acres", "REIT acquisition", "Multi-tenant", "Off-market transaction", "Hamilton growth story"]),
    listingBrokerage: "JLL Canada",
    priceHistory: [
      { price: 72000000, date: new Date("2025-01-10"), priceType: "ASKING" },
      { price: 69800000, date: new Date("2025-06-15"), priceType: "SOLD" },
    ],
  },
  {
    address: "1550 Upper James St",
    city: "Hamilton",
    neighborhood: "Hamilton Mountain",
    submarket: "Hamilton Mountain Retail",
    lat: 43.2159,
    lng: -79.8752,
    propertyType: "RETAIL",
    propertySubtype: "Power Centre",
    zoning: "C5",
    buildingSize: 58000,
    lotSize: 380000,
    yearBuilt: 1994,
    numFloors: 1,
    parkingSpaces: 420,
    status: "FOR_SALE",
    askingPrice: 24200000,
    listedDate: new Date("2025-09-10"),
    daysOnMarket: 81,
    noi: 1887600,
    capRate: 0.078,
    pricePerSqFt: 417.2,
    grossRevenue: 2494000,
    operatingExpenses: 606400,
    vacancyRate: 0.05,
    taxesAnnual: 286000,
    description: "Dominant Hamilton Mountain power centre with national anchor tenants. Strong household incomes and dense residential density. Active management driving rental rate improvement.",
    highlights: JSON.stringify(["Dominant market position", "National anchors", "Hamilton Mountain demographics", "Significant parking", "Value-add potential"]),
    listingBrokerage: "Cushman & Wakefield",
    tenants: [
      { name: "Winners", industry: "Off-Price Retail", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2029-01-31"), rentPerSqFt: 25, squareFeet: 26000, creditRating: "Investment Grade" },
      { name: "Best Buy Canada", industry: "Electronics Retail", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2027-08-31"), rentPerSqFt: 30, squareFeet: 18000, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 24200000, date: new Date("2025-09-10"), priceType: "ASKING" },
      { price: 18400000, date: new Date("2019-02-14"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },

  // === OTTAWA ===
  {
    address: "130 Slater St",
    city: "Ottawa",
    neighborhood: "Downtown Ottawa",
    submarket: "Ottawa CBD",
    lat: 45.4221,
    lng: -75.6939,
    propertyType: "OFFICE",
    propertySubtype: "Class A Office",
    zoning: "MD",
    buildingSize: 78000,
    lotSize: 18500,
    yearBuilt: 1982,
    numFloors: 15,
    parkingSpaces: 85,
    status: "FOR_SALE",
    askingPrice: 36800000,
    listedDate: new Date("2025-11-05"),
    daysOnMarket: 55,
    noi: 2357600,
    capRate: 0.064,
    pricePerSqFt: 471.8,
    grossRevenue: 3120000,
    operatingExpenses: 762400,
    vacancyRate: 0.08,
    taxesAnnual: 412000,
    description: "Premier CBD office tower steps from Parliament Hill and federal government tenants. Ideal for government and legal/lobbying tenants. Stable income with federal government anchor.",
    highlights: JSON.stringify(["Steps to Parliament", "Government anchor tenants", "LRT O-Train steps away", "Legal/lobbying proximity", "Ottawa CBD core"]),
    listingBrokerage: "CBRE Ottawa",
    tenants: [
      { name: "Government of Canada", industry: "Federal Government", leaseType: "GROSS", leaseExpiry: new Date("2031-03-31"), rentPerSqFt: 28, squareFeet: 45000, percentageOfBuilding: 57.7, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 36800000, date: new Date("2025-11-05"), priceType: "ASKING" },
      { price: 28400000, date: new Date("2020-10-15"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "2 Binnington Ct",
    city: "Ottawa",
    neighborhood: "Hunt Club Business Park",
    submarket: "Ottawa South Industrial",
    lat: 45.3628,
    lng: -75.6952,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Light Industrial",
    zoning: "IL",
    buildingSize: 86000,
    lotSize: 198000,
    yearBuilt: 1999,
    numFloors: 1,
    parkingSpaces: 105,
    loadingDocks: 10,
    clearHeight: 22,
    status: "FOR_SALE",
    askingPrice: 30400000,
    listedDate: new Date("2025-10-01"),
    daysOnMarket: 90,
    noi: 2188800,
    capRate: 0.072,
    pricePerSqFt: 353.5,
    grossRevenue: 2752000,
    operatingExpenses: 563200,
    vacancyRate: 0.05,
    taxesAnnual: 248000,
    description: "Well-located Ottawa industrial property in established south Ottawa business park. Multi-tenant with mix of government and technology tenants. Solid Ottawa market fundamentals.",
    highlights: JSON.stringify(["Government/tech tenants", "South Ottawa industrial node", "Airport proximity", "Multi-tenant diversification"]),
    listingBrokerage: "JLL Ottawa",
    priceHistory: [
      { price: 30400000, date: new Date("2025-10-01"), priceType: "ASKING" },
      { price: 18800000, date: new Date("2017-06-22"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "1200 St. Laurent Blvd",
    city: "Ottawa",
    neighborhood: "Vanier",
    submarket: "Ottawa East Retail",
    lat: 45.4386,
    lng: -75.6484,
    propertyType: "RETAIL",
    propertySubtype: "Community Shopping Centre",
    zoning: "AM",
    buildingSize: 72000,
    lotSize: 420000,
    yearBuilt: 1978,
    numFloors: 1,
    parkingSpaces: 580,
    status: "SOLD",
    askingPrice: 30200000,
    soldPrice: 28600000,
    soldDate: new Date("2025-10-08"),
    listedDate: new Date("2025-04-15"),
    daysOnMarket: 176,
    noi: 2144000,
    capRate: 0.075,
    pricePerSqFt: 397.2,
    grossRevenue: 2736000,
    operatingExpenses: 592000,
    vacancyRate: 0.08,
    taxesAnnual: 328000,
    description: "Dominant community shopping centre sold in Ottawa's east end. Grocery anchor with diverse retail mix. Strong redevelopment potential with large surface parking lot.",
    highlights: JSON.stringify(["Grocery anchor", "Redevelopment potential", "Large surface lot", "Established Ottawa retail node"]),
    listingBrokerage: "Colliers Ottawa",
    priceHistory: [
      { price: 30200000, date: new Date("2025-04-15"), priceType: "ASKING" },
      { price: 28600000, date: new Date("2025-10-08"), priceType: "SOLD" },
      { price: 17200000, date: new Date("2014-08-20"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "111 Lisgar St",
    city: "Ottawa",
    neighborhood: "Centretown",
    submarket: "Ottawa CBD",
    lat: 45.4185,
    lng: -75.6973,
    propertyType: "OFFICE",
    propertySubtype: "Class B Office",
    zoning: "MD",
    buildingSize: 42000,
    lotSize: 12000,
    yearBuilt: 1974,
    numFloors: 10,
    parkingSpaces: 48,
    status: "FOR_SALE",
    askingPrice: 15600000,
    listedDate: new Date("2025-07-01"),
    daysOnMarket: 152,
    noi: 1248000,
    capRate: 0.080,
    pricePerSqFt: 371.4,
    grossRevenue: 1596000,
    operatingExpenses: 348000,
    vacancyRate: 0.18,
    taxesAnnual: 184000,
    description: "Centretown office tower presenting value-add opportunity in recovering Ottawa CBD market. High vacancy creates compelling lease-up story. LRT O-Train at Centretown Station steps away.",
    highlights: JSON.stringify(["Value-add lease-up story", "LRT steps away", "Near Parliament Hill", "Below-market asking rents", "Conversion potential"]),
    listingBrokerage: "Avison Young Ottawa",
    priceHistory: [
      { price: 17800000, date: new Date("2025-04-01"), priceType: "ASKING" },
      { price: 15600000, date: new Date("2025-07-01"), priceType: "PRICE_CHANGE" },
    ],
  },
  {
    address: "2197 Riverside Dr",
    city: "Ottawa",
    neighborhood: "Riverside Park",
    submarket: "Ottawa South Residential",
    lat: 45.3842,
    lng: -75.6728,
    propertyType: "MULTIFAMILY",
    propertySubtype: "Apartment Building",
    zoning: "R5B",
    buildingSize: 58000,
    lotSize: 28000,
    yearBuilt: 1978,
    numFloors: 8,
    numUnits: 52,
    parkingSpaces: 58,
    status: "FOR_SALE",
    askingPrice: 19800000,
    listedDate: new Date("2025-11-20"),
    daysOnMarket: 40,
    noi: 1029600,
    capRate: 0.052,
    pricePerSqFt: 341.4,
    grossRevenue: 1435200,
    operatingExpenses: 405600,
    vacancyRate: 0.02,
    taxesAnnual: 164000,
    description: "Well-maintained 52-unit apartment building on the Rideau River. Excellent suite mix with 1BR and 2BR suites. Stabilized income with significant rental upside given below-market rents.",
    highlights: JSON.stringify(["Rideau River views", "52 units", "Below-market rents", "Strong Ottawa rental demand", "Riverside Park location"]),
    listingBrokerage: "Marcus & Millichap Ottawa",
    priceHistory: [
      { price: 19800000, date: new Date("2025-11-20"), priceType: "ASKING" },
      { price: 11200000, date: new Date("2015-06-08"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },

  // === VAUGHAN ===
  {
    address: "3600 Steeles Ave W",
    city: "Vaughan",
    neighborhood: "Concord",
    submarket: "Vaughan Industrial",
    lat: 43.7868,
    lng: -79.5284,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Distribution/Logistics",
    zoning: "EM1",
    buildingSize: 218000,
    lotSize: 615000,
    yearBuilt: 2005,
    numFloors: 1,
    parkingSpaces: 268,
    loadingDocks: 38,
    clearHeight: 32,
    status: "FOR_SALE",
    askingPrice: 98600000,
    listedDate: new Date("2025-09-15"),
    daysOnMarket: 76,
    noi: 5616000,
    capRate: 0.057,
    pricePerSqFt: 452.3,
    grossRevenue: 6988000,
    operatingExpenses: 1372000,
    vacancyRate: 0.0,
    taxesAnnual: 728000,
    description: "Marquee Vaughan industrial complex on 14.1 acres. Modern distribution facility with 32-foot clear height, extensive dock count, and full site coverage. Fully leased to two-tenant roster.",
    highlights: JSON.stringify(["14.1 acres", "32' clear height", "38 dock doors", "Two-tenant roster", "Highway 400/407 access"]),
    listingBrokerage: "JLL Canada",
    tenants: [
      { name: "Sobeys Inc.", industry: "Food Distribution", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2032-12-31"), rentPerSqFt: 28, squareFeet: 140000, creditRating: "Investment Grade" },
      { name: "GFL Environmental", industry: "Waste Management", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2030-06-30"), rentPerSqFt: 24, squareFeet: 78000, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 98600000, date: new Date("2025-09-15"), priceType: "ASKING" },
      { price: 58400000, date: new Date("2019-04-12"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "400 Applewood Crescent",
    city: "Vaughan",
    neighborhood: "Concord",
    submarket: "Vaughan Industrial",
    lat: 43.7905,
    lng: -79.5248,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Light Industrial",
    zoning: "EM1",
    buildingSize: 82000,
    lotSize: 195000,
    yearBuilt: 1993,
    numFloors: 1,
    parkingSpaces: 96,
    loadingDocks: 12,
    clearHeight: 22,
    status: "SOLD",
    askingPrice: 34800000,
    soldPrice: 33400000,
    soldDate: new Date("2025-09-05"),
    listedDate: new Date("2025-05-10"),
    daysOnMarket: 118,
    noi: 2038000,
    capRate: 0.061,
    pricePerSqFt: 407.3,
    grossRevenue: 2542000,
    operatingExpenses: 504000,
    vacancyRate: 0.0,
    taxesAnnual: 248000,
    description: "Fully leased Vaughan industrial asset sold in Q3 2025. Well-located within established Concord industrial park. Multi-tenant with strong lease terms providing near-term mark-to-market upside.",
    highlights: JSON.stringify(["Fully leased", "Multi-tenant", "Mark-to-market upside", "Hwy 400 proximity"]),
    listingBrokerage: "Colliers International",
    priceHistory: [
      { price: 34800000, date: new Date("2025-05-10"), priceType: "ASKING" },
      { price: 33400000, date: new Date("2025-09-05"), priceType: "SOLD" },
      { price: 19600000, date: new Date("2018-02-28"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "55 Commerce Valley Dr E",
    city: "Markham",
    neighborhood: "Commerce Valley",
    submarket: "Markham Office",
    lat: 43.8458,
    lng: -79.3994,
    propertyType: "OFFICE",
    propertySubtype: "Class A Office",
    zoning: "OP",
    buildingSize: 55000,
    lotSize: 42000,
    yearBuilt: 2000,
    numFloors: 7,
    parkingSpaces: 220,
    status: "FOR_SALE",
    askingPrice: 26200000,
    listedDate: new Date("2025-10-22"),
    daysOnMarket: 68,
    noi: 1806200,
    capRate: 0.069,
    pricePerSqFt: 476.4,
    grossRevenue: 2420000,
    operatingExpenses: 613800,
    vacancyRate: 0.10,
    taxesAnnual: 312000,
    description: "Modern suburban office building in Markham's prestigious Commerce Valley business park. LEED Certified with excellent parking ratio. Strong tech sector tenant demand in Markham.",
    highlights: JSON.stringify(["LEED Certified", "Tech sector location", "Excellent parking ratio", "404/407 access", "Commerce Valley prestige"]),
    listingBrokerage: "CBRE Canada",
    priceHistory: [
      { price: 26200000, date: new Date("2025-10-22"), priceType: "ASKING" },
      { price: 19800000, date: new Date("2020-01-15"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "3650 Victoria Park Ave",
    city: "Toronto",
    neighborhood: "L'Amoreaux",
    submarket: "North York Industrial",
    lat: 43.7820,
    lng: -79.3312,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Industrial Flex",
    zoning: "EH",
    buildingSize: 72000,
    lotSize: 168000,
    yearBuilt: 1976,
    numFloors: 1,
    parkingSpaces: 88,
    loadingDocks: 8,
    clearHeight: 18,
    status: "FOR_SALE",
    askingPrice: 30600000,
    listedDate: new Date("2025-08-25"),
    daysOnMarket: 97,
    noi: 1927800,
    capRate: 0.063,
    pricePerSqFt: 425.0,
    grossRevenue: 2376000,
    operatingExpenses: 448200,
    vacancyRate: 0.05,
    taxesAnnual: 228000,
    description: "Established infill industrial flex property in high-demand north Toronto industrial corridor. Excellent highway access, close to Hwy 401 and 404. Urban infill location with land value.",
    highlights: JSON.stringify(["Urban infill", "Highway 401/404 access", "Land value upside", "Multi-tenant", "North Toronto industrial premium"]),
    listingBrokerage: "Avison Young",
    priceHistory: [
      { price: 30600000, date: new Date("2025-08-25"), priceType: "ASKING" },
      { price: 16400000, date: new Date("2016-11-18"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "7777 Warden Ave",
    city: "Markham",
    neighborhood: "Milliken",
    submarket: "Markham Industrial",
    lat: 43.8228,
    lng: -79.3428,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Warehouse/Distribution",
    zoning: "M",
    buildingSize: 138000,
    lotSize: 368000,
    yearBuilt: 1988,
    numFloors: 1,
    parkingSpaces: 165,
    loadingDocks: 20,
    clearHeight: 22,
    status: "SOLD",
    askingPrice: 59200000,
    soldPrice: 57800000,
    soldDate: new Date("2025-11-28"),
    listedDate: new Date("2025-07-22"),
    daysOnMarket: 129,
    noi: 3411000,
    capRate: 0.059,
    pricePerSqFt: 418.8,
    grossRevenue: 4200000,
    operatingExpenses: 789000,
    vacancyRate: 0.0,
    taxesAnnual: 428000,
    description: "Significant Markham industrial sold November 2025 to institutional buyer. 8.45-acre site fully leased with long WALT. Strong Markham industrial market fundamentals.",
    highlights: JSON.stringify(["8.45 acres", "Institutional acquisition", "Long WALT", "Markham industrial core", "404 proximity"]),
    listingBrokerage: "JLL Canada",
    priceHistory: [
      { price: 59200000, date: new Date("2025-07-22"), priceType: "ASKING" },
      { price: 57800000, date: new Date("2025-11-28"), priceType: "SOLD" },
      { price: 34200000, date: new Date("2019-09-06"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "3085 Kennedy Rd",
    city: "Toronto",
    neighborhood: "Agincourt",
    submarket: "Scarborough Industrial",
    lat: 43.7786,
    lng: -79.2748,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Industrial Flex",
    zoning: "EH",
    buildingSize: 50000,
    lotSize: 128000,
    yearBuilt: 1984,
    numFloors: 1,
    parkingSpaces: 64,
    loadingDocks: 6,
    clearHeight: 20,
    status: "FOR_SALE",
    askingPrice: 21800000,
    listedDate: new Date("2025-12-01"),
    daysOnMarket: 29,
    noi: 1481200,
    capRate: 0.068,
    pricePerSqFt: 436.0,
    grossRevenue: 1800000,
    operatingExpenses: 318800,
    vacancyRate: 0.08,
    taxingAnnual: 168000,
    taxesAnnual: 168000,
    description: "Value-add industrial flex opportunity in Scarborough. Near-term lease rollovers provide opportunity to mark rents to market. Kennedy/Sheppard intersection with strong industrial node.",
    highlights: JSON.stringify(["Value-add play", "Rent mark-to-market", "Scarborough prime location", "Kennedy/Sheppard node"]),
    listingBrokerage: "Marcus & Millichap",
    priceHistory: [
      { price: 21800000, date: new Date("2025-12-01"), priceType: "ASKING" },
    ],
  },
  {
    address: "191 Allstate Pkwy",
    city: "Markham",
    neighborhood: "Markham Business Park",
    submarket: "Markham Office",
    lat: 43.8528,
    lng: -79.3648,
    propertyType: "OFFICE",
    propertySubtype: "Class B Office",
    zoning: "OP",
    buildingSize: 44000,
    lotSize: 38000,
    yearBuilt: 1988,
    numFloors: 5,
    parkingSpaces: 180,
    status: "FOR_SALE",
    askingPrice: 17800000,
    listedDate: new Date("2025-07-18"),
    daysOnMarket: 165,
    noi: 1352800,
    capRate: 0.076,
    pricePerSqFt: 404.5,
    grossRevenue: 1716000,
    operatingExpenses: 363200,
    vacancyRate: 0.12,
    taxesAnnual: 186000,
    description: "Suburban office opportunity in Markham's tech corridor with below-market rents and significant value-add potential. Strong local tech employment base driving office demand recovery.",
    highlights: JSON.stringify(["Markham tech corridor", "Value-add lease-up", "401/407 access", "Good parking ratio", "Below market rents"]),
    listingBrokerage: "Cushman & Wakefield",
    priceHistory: [
      { price: 19200000, date: new Date("2025-04-15"), priceType: "ASKING" },
      { price: 17800000, date: new Date("2025-07-18"), priceType: "PRICE_CHANGE" },
    ],
  },
  {
    address: "1 Bass Pro Mills Dr",
    city: "Vaughan",
    neighborhood: "Vaughan Mills",
    submarket: "Vaughan Retail",
    lat: 43.8302,
    lng: -79.5368,
    propertyType: "RETAIL",
    propertySubtype: "Big Box Retail",
    zoning: "C6",
    buildingSize: 38500,
    lotSize: 182000,
    yearBuilt: 2004,
    numFloors: 1,
    parkingSpaces: 385,
    status: "FOR_SALE",
    askingPrice: 17400000,
    listedDate: new Date("2025-10-05"),
    daysOnMarket: 85,
    noi: 1113600,
    capRate: 0.064,
    pricePerSqFt: 451.9,
    grossRevenue: 1386000,
    operatingExpenses: 272400,
    vacancyRate: 0.0,
    taxesAnnual: 186000,
    description: "Single-tenant big box retail adjacent to Vaughan Mills shopping centre. Long-term NNN lease to national sporting goods tenant. Excellent location in one of Ontario's highest-traffic retail nodes.",
    highlights: JSON.stringify(["Adjacent to Vaughan Mills", "Single tenant NNN", "National tenant", "High traffic location", "400/407 access"]),
    listingBrokerage: "Royal LePage Commercial",
    tenants: [
      { name: "Bass Pro Shops", industry: "Sporting Goods", leaseType: "TRIPLE_NET", leaseExpiry: new Date("2033-06-30"), rentPerSqFt: 36, squareFeet: 38500, percentageOfBuilding: 100, creditRating: "Investment Grade" },
    ],
    priceHistory: [
      { price: 17400000, date: new Date("2025-10-05"), priceType: "ASKING" },
      { price: 12800000, date: new Date("2017-08-22"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "350 Rutherford Rd S",
    city: "Brampton",
    neighborhood: "Brampton East Industrial",
    submarket: "Brampton Industrial",
    lat: 43.6682,
    lng: -79.6928,
    propertyType: "INDUSTRIAL",
    propertySubtype: "Industrial Flex",
    zoning: "M2",
    buildingSize: 58000,
    lotSize: 148000,
    yearBuilt: 1995,
    numFloors: 1,
    parkingSpaces: 72,
    loadingDocks: 6,
    clearHeight: 20,
    status: "FOR_SALE",
    askingPrice: 26400000,
    listedDate: new Date("2025-11-12"),
    daysOnMarket: 48,
    noi: 1715200,
    capRate: 0.065,
    pricePerSqFt: 455.2,
    grossRevenue: 2088000,
    operatingExpenses: 372800,
    vacancyRate: 0.05,
    taxesAnnual: 186000,
    description: "Quality industrial flex in Brampton's growing east industrial area. Split between warehouse and office. Near Hwy 410 with easy access to the Greater Toronto Area.",
    highlights: JSON.stringify(["Quality flex industrial", "Office/warehouse split", "Hwy 410 access", "Growing Brampton submarket"]),
    listingBrokerage: "Avison Young",
    priceHistory: [
      { price: 26400000, date: new Date("2025-11-12"), priceType: "ASKING" },
      { price: 14200000, date: new Date("2016-03-10"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "875 Carling Ave",
    city: "Ottawa",
    neighborhood: "Civic Hospital",
    submarket: "Ottawa West",
    lat: 45.3985,
    lng: -75.7318,
    propertyType: "MIXED_USE",
    propertySubtype: "Retail/Residential Mixed",
    zoning: "TM",
    buildingSize: 26000,
    lotSize: 12000,
    yearBuilt: 1968,
    numFloors: 5,
    numUnits: 18,
    parkingSpaces: 28,
    status: "FOR_SALE",
    askingPrice: 11600000,
    listedDate: new Date("2025-09-25"),
    daysOnMarket: 85,
    noi: 823600,
    capRate: 0.071,
    pricePerSqFt: 446.2,
    grossRevenue: 1118400,
    operatingExpenses: 294800,
    vacancyRate: 0.03,
    taxesAnnual: 98000,
    description: "Mixed-use building near Ottawa's Civic Hospital with ground floor medical/retail and upper floor apartments. Stable medical office tenancy driven by hospital proximity.",
    highlights: JSON.stringify(["Medical/hospital proximity", "Stable tenancy", "Transit on Carling", "Mixed income streams"]),
    listingBrokerage: "JLL Ottawa",
    priceHistory: [
      { price: 11600000, date: new Date("2025-09-25"), priceType: "ASKING" },
      { price: 7200000, date: new Date("2018-05-08"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "2468 Lake Shore Blvd W",
    city: "Toronto",
    neighborhood: "Mimico",
    submarket: "West Toronto Retail",
    lat: 43.6192,
    lng: -79.4872,
    propertyType: "MIXED_USE",
    propertySubtype: "Retail/Residential Mixed",
    zoning: "CR2.5",
    buildingSize: 15500,
    lotSize: 11200,
    yearBuilt: 1948,
    numFloors: 3,
    numUnits: 8,
    parkingSpaces: 12,
    status: "FOR_SALE",
    askingPrice: 8900000,
    listedDate: new Date("2025-11-08"),
    daysOnMarket: 52,
    noi: 542900,
    capRate: 0.061,
    pricePerSqFt: 574.2,
    grossRevenue: 763200,
    operatingExpenses: 220300,
    vacancyRate: 0.0,
    taxesAnnual: 68000,
    description: "Lakeside mixed-use building in Mimico's resurgent retail strip. Ground floor retail with two upper floors of residential apartments. Lake Ontario views and GO Train steps away.",
    highlights: JSON.stringify(["Mimico GO Train steps", "Lake views", "100% occupied", "Gentrifying corridor", "Redevelopment potential"]),
    listingBrokerage: "Cushman & Wakefield",
    priceHistory: [
      { price: 8900000, date: new Date("2025-11-08"), priceType: "ASKING" },
      { price: 4800000, date: new Date("2015-10-22"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
  {
    address: "350 Sparks St",
    city: "Ottawa",
    neighborhood: "Centretown",
    submarket: "Ottawa CBD",
    lat: 45.4208,
    lng: -75.6994,
    propertyType: "RETAIL",
    propertySubtype: "Street Retail / Pedestrian Mall",
    zoning: "MD",
    buildingSize: 24000,
    lotSize: 9600,
    yearBuilt: 1965,
    numFloors: 3,
    parkingSpaces: 0,
    status: "FOR_SALE",
    askingPrice: 12200000,
    listedDate: new Date("2025-08-05"),
    daysOnMarket: 117,
    noi: 841800,
    capRate: 0.069,
    pricePerSqFt: 508.3,
    grossRevenue: 1128000,
    operatingExpenses: 286200,
    vacancyRate: 0.08,
    taxesAnnual: 116000,
    description: "Prime Sparks Street pedestrian mall building with government and professional tenants. Ottawa's most prominent retail address with strong government sector foot traffic.",
    highlights: JSON.stringify(["Sparks Street pedestrian mall", "Government foot traffic", "Parliamentary precinct", "Landmark Ottawa address"]),
    listingBrokerage: "Colliers Ottawa",
    priceHistory: [
      { price: 12200000, date: new Date("2025-08-05"), priceType: "ASKING" },
      { price: 9400000, date: new Date("2019-11-15"), priceType: "SOLD", notes: "Prior sale" },
    ],
  },
];

const marketData = [
  // Toronto
  { city: "Toronto", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.059, avgPricePerSqFt: 428, totalVolume: 1240000000, numTransactions: 42, avgDaysOnMarket: 68, vacancyRate: 0.018, yoyPriceChange: 0.082 },
  { city: "Toronto", propertyType: "INDUSTRIAL", period: "2025-Q2", avgCapRate: 0.061, avgPricePerSqFt: 412, totalVolume: 980000000, numTransactions: 38, avgDaysOnMarket: 72, vacancyRate: 0.022, yoyPriceChange: 0.078 },
  { city: "Toronto", propertyType: "INDUSTRIAL", period: "2025-Q1", avgCapRate: 0.062, avgPricePerSqFt: 398, totalVolume: 860000000, numTransactions: 31, avgDaysOnMarket: 84, vacancyRate: 0.024, yoyPriceChange: 0.068 },
  { city: "Toronto", propertyType: "INDUSTRIAL", period: "2024-Q4", avgCapRate: 0.058, avgPricePerSqFt: 385, totalVolume: 1420000000, numTransactions: 56, avgDaysOnMarket: 62, vacancyRate: 0.016, yoyPriceChange: 0.112 },
  { city: "Toronto", propertyType: "OFFICE", period: "2025-Q3", avgCapRate: 0.071, avgPricePerSqFt: 498, totalVolume: 640000000, numTransactions: 18, avgDaysOnMarket: 128, vacancyRate: 0.138, yoyPriceChange: -0.028 },
  { city: "Toronto", propertyType: "OFFICE", period: "2025-Q2", avgCapRate: 0.072, avgPricePerSqFt: 482, totalVolume: 520000000, numTransactions: 14, avgDaysOnMarket: 142, vacancyRate: 0.144, yoyPriceChange: -0.032 },
  { city: "Toronto", propertyType: "OFFICE", period: "2025-Q1", avgCapRate: 0.074, avgPricePerSqFt: 468, totalVolume: 380000000, numTransactions: 11, avgDaysOnMarket: 158, vacancyRate: 0.148, yoyPriceChange: -0.038 },
  { city: "Toronto", propertyType: "OFFICE", period: "2024-Q4", avgCapRate: 0.069, avgPricePerSqFt: 512, totalVolume: 780000000, numTransactions: 22, avgDaysOnMarket: 118, vacancyRate: 0.128, yoyPriceChange: -0.018 },
  { city: "Toronto", propertyType: "RETAIL", period: "2025-Q3", avgCapRate: 0.062, avgPricePerSqFt: 542, totalVolume: 480000000, numTransactions: 24, avgDaysOnMarket: 94, vacancyRate: 0.048, yoyPriceChange: 0.042 },
  { city: "Toronto", propertyType: "RETAIL", period: "2025-Q2", avgCapRate: 0.064, avgPricePerSqFt: 524, totalVolume: 420000000, numTransactions: 21, avgDaysOnMarket: 102, vacancyRate: 0.052, yoyPriceChange: 0.038 },
  { city: "Toronto", propertyType: "RETAIL", period: "2025-Q1", avgCapRate: 0.065, avgPricePerSqFt: 506, totalVolume: 360000000, numTransactions: 18, avgDaysOnMarket: 112, vacancyRate: 0.056, yoyPriceChange: 0.028 },
  { city: "Toronto", propertyType: "RETAIL", period: "2024-Q4", avgCapRate: 0.061, avgPricePerSqFt: 558, totalVolume: 680000000, numTransactions: 32, avgDaysOnMarket: 86, vacancyRate: 0.044, yoyPriceChange: 0.055 },
  { city: "Toronto", propertyType: "MULTIFAMILY", period: "2025-Q3", avgCapRate: 0.043, avgPricePerSqFt: 412, totalVolume: 820000000, numTransactions: 28, avgDaysOnMarket: 54, vacancyRate: 0.012, yoyPriceChange: 0.062 },
  { city: "Toronto", propertyType: "MULTIFAMILY", period: "2025-Q2", avgCapRate: 0.044, avgPricePerSqFt: 398, totalVolume: 740000000, numTransactions: 24, avgDaysOnMarket: 58, vacancyRate: 0.014, yoyPriceChange: 0.058 },
  // Mississauga
  { city: "Mississauga", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.058, avgPricePerSqFt: 458, totalVolume: 680000000, numTransactions: 28, avgDaysOnMarket: 72, vacancyRate: 0.024, yoyPriceChange: 0.068 },
  { city: "Mississauga", propertyType: "INDUSTRIAL", period: "2025-Q2", avgCapRate: 0.060, avgPricePerSqFt: 442, totalVolume: 540000000, numTransactions: 22, avgDaysOnMarket: 82, vacancyRate: 0.028, yoyPriceChange: 0.062 },
  { city: "Mississauga", propertyType: "OFFICE", period: "2025-Q3", avgCapRate: 0.068, avgPricePerSqFt: 452, totalVolume: 320000000, numTransactions: 12, avgDaysOnMarket: 118, vacancyRate: 0.158, yoyPriceChange: -0.022 },
  { city: "Mississauga", propertyType: "RETAIL", period: "2025-Q3", avgCapRate: 0.069, avgPricePerSqFt: 412, totalVolume: 240000000, numTransactions: 14, avgDaysOnMarket: 98, vacancyRate: 0.058, yoyPriceChange: 0.028 },
  // Hamilton
  { city: "Hamilton", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.072, avgPricePerSqFt: 328, totalVolume: 420000000, numTransactions: 18, avgDaysOnMarket: 88, vacancyRate: 0.028, yoyPriceChange: 0.092 },
  { city: "Hamilton", propertyType: "INDUSTRIAL", period: "2025-Q2", avgCapRate: 0.074, avgPricePerSqFt: 312, totalVolume: 340000000, numTransactions: 14, avgDaysOnMarket: 96, vacancyRate: 0.032, yoyPriceChange: 0.085 },
  { city: "Hamilton", propertyType: "RETAIL", period: "2025-Q3", avgCapRate: 0.076, avgPricePerSqFt: 378, totalVolume: 180000000, numTransactions: 10, avgDaysOnMarket: 104, vacancyRate: 0.068, yoyPriceChange: 0.022 },
  // Ottawa
  { city: "Ottawa", propertyType: "OFFICE", period: "2025-Q3", avgCapRate: 0.072, avgPricePerSqFt: 428, totalVolume: 480000000, numTransactions: 16, avgDaysOnMarket: 108, vacancyRate: 0.128, yoyPriceChange: -0.018 },
  { city: "Ottawa", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.069, avgPricePerSqFt: 342, totalVolume: 280000000, numTransactions: 12, avgDaysOnMarket: 92, vacancyRate: 0.032, yoyPriceChange: 0.072 },
  { city: "Ottawa", propertyType: "RETAIL", period: "2025-Q3", avgCapRate: 0.072, avgPricePerSqFt: 398, totalVolume: 220000000, numTransactions: 10, avgDaysOnMarket: 112, vacancyRate: 0.062, yoyPriceChange: 0.018 },
  // Vaughan/Markham
  { city: "Vaughan", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.057, avgPricePerSqFt: 448, totalVolume: 560000000, numTransactions: 22, avgDaysOnMarket: 76, vacancyRate: 0.018, yoyPriceChange: 0.078 },
  { city: "Markham", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.060, avgPricePerSqFt: 418, totalVolume: 380000000, numTransactions: 16, avgDaysOnMarket: 84, vacancyRate: 0.022, yoyPriceChange: 0.068 },
  { city: "Brampton", propertyType: "INDUSTRIAL", period: "2025-Q3", avgCapRate: 0.061, avgPricePerSqFt: 438, totalVolume: 480000000, numTransactions: 18, avgDaysOnMarket: 78, vacancyRate: 0.020, yoyPriceChange: 0.074 },
];

async function main() {
  console.log("Seeding database...");

  // Create demo user
  const hashedPassword = await bcrypt.hash("demo1234", 12);
  await prisma.user.upsert({
    where: { email: "demo@commercial-sigma.ca" },
    update: {},
    create: {
      email: "demo@commercial-sigma.ca",
      password: hashedPassword,
      name: "Demo User",
      company: "Sigma Capital Group",
      role: "USER",
    },
  });

  // Seed properties
  for (const prop of properties) {
    const { tenants, priceHistory, ...propData } = prop as {
      tenants?: Array<{
        name: string;
        industry?: string;
        leaseType?: string;
        leaseExpiry?: Date;
        leaseStart?: Date;
        rentPerSqFt?: number;
        squareFeet?: number;
        percentageOfBuilding?: number;
        creditRating?: string;
      }>;
      priceHistory?: Array<{
        price: number;
        date: Date;
        priceType: string;
        notes?: string;
      }>;
      taxingAnnual?: number;
      [key: string]: unknown;
    };

    const created = await prisma.property.create({
      data: {
        address: propData.address as string,
        city: propData.city as string,
        province: (propData.province as string) ?? "ON",
        postalCode: propData.postalCode as string | undefined,
        lat: propData.lat as number,
        lng: propData.lng as number,
        neighborhood: propData.neighborhood as string | undefined,
        submarket: propData.submarket as string | undefined,
        propertyType: propData.propertyType as string,
        propertySubtype: propData.propertySubtype as string | undefined,
        zoning: propData.zoning as string | undefined,
        buildingSize: propData.buildingSize as number,
        lotSize: propData.lotSize as number | undefined,
        yearBuilt: propData.yearBuilt as number | undefined,
        numFloors: propData.numFloors as number | undefined,
        numUnits: propData.numUnits as number | undefined,
        parkingSpaces: propData.parkingSpaces as number | undefined,
        loadingDocks: propData.loadingDocks as number | undefined,
        clearHeight: propData.clearHeight as number | undefined,
        status: propData.status as string,
        askingPrice: propData.askingPrice as number | undefined,
        soldPrice: propData.soldPrice as number | undefined,
        soldDate: propData.soldDate as Date | undefined,
        listedDate: propData.listedDate as Date | undefined,
        daysOnMarket: propData.daysOnMarket as number | undefined,
        noi: propData.noi as number | undefined,
        capRate: propData.capRate as number | undefined,
        grm: propData.grm as number | undefined,
        pricePerSqFt: propData.pricePerSqFt as number | undefined,
        grossRevenue: propData.grossRevenue as number | undefined,
        operatingExpenses: propData.operatingExpenses as number | undefined,
        vacancyRate: propData.vacancyRate as number | undefined,
        taxesAnnual: propData.taxesAnnual as number | undefined,
        description: propData.description as string | undefined,
        highlights: propData.highlights as string | undefined,
        images: "[]",
        listingBrokerage: propData.listingBrokerage as string | undefined,
      },
    });

    if (tenants && tenants.length > 0) {
      await prisma.tenant.createMany({
        data: tenants.map((t) => ({ ...t, propertyId: created.id })),
      });
    }

    if (priceHistory && priceHistory.length > 0) {
      await prisma.priceHistory.createMany({
        data: priceHistory.map((ph) => ({ ...ph, propertyId: created.id })),
      });
    }
  }

  // Seed market data
  await prisma.marketData.createMany({ data: marketData });

  console.log(`Seeded ${properties.length} properties and ${marketData.length} market data records.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
